Added docker setup
9d8dev/router pull request #13
Opened 2024-09-07 05:57 UTC by ArpitBlagan

https://www.loom.com/share/36b8e5a3b8724c5a901a10c445ad6a75?sid=198c0357-275d-4c54-a034-47e8597a8b5b

2024-09-09 17:19 UTC, youngbloodcyb requested changes
Love this, thanks for taking this on. 

Only thing is looks like prettier config is different and it's changing double quotes to single quotes throughout the whole codebase. Can you update that to match the current codebase?

2024-09-09 17:48 UTC, ArpitBlagan commented
> Love this, thanks for taking this on.
> 
> Only thing is looks like prettier config is different and it's changing double quotes to single quotes throughout the whole codebase. Can you update that to match the current codebase?

prettierrc is updated you can check now

2024-09-10 14:00 UTC, vtfg commented
It would be great if you replaced all relative imports (../ui i.e.) with absolute imports (@/components/ui).

2024-09-10 14:09 UTC, ArpitBlagan commented
> It would be great if you replaced all relative imports (../ui i.e.) with absolute imports (@/components/ui).

can you tell me where I am using relative imports that will be helpfull

2024-09-10 14:17 UTC, vtfg commented
Not you, but there are some relative imports in some files. Since you are linting them all, you could padronize everything.

Search for "../" in VSCode and update them to use absolute imports, like this:

- `../components` => `@/components/`
- `../ui` => `@/components/ui`
- `../auth` => `@/components/auth`
- `../lib` => `@/lib`
- `../db` => `@/lib/db`

2024-09-10 14:19 UTC, ArpitBlagan commented
> Not you, but there are some relative imports in some files. Since you are linting them all, you could padronize everything.
> 
> Search for `../` in VSCode and update them to use absolute imports, like this:
> 
> * `../components` => `@/components/`
> * `../ui` => `@/components/ui`
> * `../auth` => `@/components/auth`
> * `../lib` => `@/lib`
> * `../db` => `@/lib/db`

okay sorry i misunderstood

2024-09-10 14:36 UTC, ArpitBlagan commented
> Not you, but there are some relative imports in some files. Since you are linting them all, you could padronize everything.
> 
> Search for `../` in VSCode and update them to use absolute imports, like this:
> 
> * `../components` => `@/components/`
> * `../ui` => `@/components/ui`
> * `../auth` => `@/components/auth`
> * `../lib` => `@/lib`
> * `../db` => `@/lib/db`
> 
> It's a code quality thing, it won't affect anything.

Done sir. 
I am currently looking for some unique project ideas to standout from the crowd if you have any please let me know @vtfg

2024-09-10 14:56 UTC, vtfg commented
> I am currently looking for some unique project ideas to standout from the crowd

"Unique" is a strong keyword. I think it is very hard to have an unique idea, specially in today's world. What you can do is: find a project you like and re-develop it, improving or adding some features.

I'm not the best guy to ask this. I also have trouble finding project ideas.

2024-09-10 15:13 UTC, vtfg commented on package.json
> +    "eslint": "^8",=
The `=` is causing an installation error.

2024-09-10 15:13 UTC, vtfg commented on docker-compose.yml
> +      - .env
The project uses the `.env.local` file.

I actually don't think that adding `env_file` here has any impact, as loading it is the Next.js/Drizzle's responsability.

> Edit: I tested and it really had no impact.

2024-09-10 16:09 UTC, youngbloodcyb requested changes
sorry to keep going back and forth on this. I'd really prefer if we kept each PR separate to its respective feature / bug. In this case since the purpose is to add capability for docker, lets focus on that. 

I think the only files that should be added / edited are the `.dockerignore`, `.husky/pre-commit` and `Dockerfile`. For adding docker there's no reason 100 files should be updated. 

Let's strip this PR down and only have the edits for those 3 files so that it's easier to review and test.

2024-09-10 16:10 UTC, ArpitBlagan commented on docker-compose.yml
> +      - .env
ooh yha let me change it to .env.local as I don't want to put the env file in the image.

2024-09-10 16:17 UTC, youngbloodcyb commented
> Not you, but there are some relative imports in some files. Since you are linting them all, you could padronize everything.
> 
> Search for `../` in VSCode and update them to use absolute imports, like this:
> 
> * `../components` => `@/components/`
> * `../ui` => `@/components/ui`
> * `../auth` => `@/components/auth`
> * `../lib` => `@/lib`
> * `../db` => `@/lib/db`
> 
> It's a code quality thing, it won't affect anything.

I think this is a great idea but would rather have this be its own PR to test. @ArpitBlagan if you'd like, you could open this up separately from the docker init

2024-09-10 16:34 UTC, ArpitBlagan commented
closing this one and creating a new separate pr's

2024-09-10 16:34 UTC, closed without merging